[platformio]
src_dir = src

[env:m5stack-sticks3]
platform = espressif32
board    = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
extra_scripts = pre:scripts/link_esp_new_jpeg.py
lib_ignore = esp_new_jpeg
build_flags =
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DLV_CONF_SKIP=1
lib_deps =
    lvgl/lvgl@^9.1.0
    m5stack/M5GFX
    m5stack/M5Unified
    esp_new_jpeg=https://components.espressif.com/api/downloads/?object_type=component&object_id=f346478b-a1a6-4eed-b903-b8658e031d87
